project_id = "zhwicjfupdbaaceerozm"

[functions.api]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.delete-admin]
verify_jwt = false